### ISSUE TITLE
Imported items give incorrect stats (Cataclysm Sim, Rogue)

### ISSUE THREAD

**Issue by NoSkills** [wowsims/cata#530]
**Describe the bug**
Using the WoWSims addon, the imported items for Cataclysm sim just give incorrect stats and I cannot really see where it does it wrong.

I have 1332 Hit in game (17% spell cap exactly), and it shows as 1212 from gear in WoWsim after importing the same gear. The reforges doesn't make sense either and it doesn't add up to 1332 and it thinks I'm not spellhit capped.

The Haste is also off by -20, and Mastery by +119 so it feels like enchants/socket bonuses and similar isn't always taken into account.
I'm not sure how it magically adds Mastery either.

**To Reproduce**
1. Use WowSimsExporter V2.10 for a Rogue character that spellhit capped
2. Import it into Wowsims for Cataclysm
3. Look at the stats summary and be bamboozled

**Expected behavior**
Expected the stats from the import to reflect the same stats that one has in game - the items, reforges, gems, etc all shows up accurately so visually it isn't anything that is 'off'. It's just that the stats summary for some reason adds or removes stats somewhere.

It is also not a visual bug, because if you Calculate EPs, it really thinks I'm under hit cap (by providing EP gain for Spell hit).
Manually cheating and adding a bonus of the remaining hit cap rating and calculating EP again makes it go down to 0 EP gain, so it is clearly missing some stats.

**Sim Links and Screenshots**
https://wowsims.github.io/cata/rogue/assassination/#eJzlU11IFFEUnnPuuDt7/NnxYjVeKbfRYtqwZmfb0CJ2iwoJIqEXo5cC+yUikqB6kqCwEBJ6MH0ziMIIyh7aiujnRcvCzSAsqCgUfdAiM/Al6s7MVqb0S28dhvvz3e/7zrn3zqV5GuiQgp2wDxoBTgOcB7gN0A8wDNCA0IhwCWEVGZJUDbWSxhVxjtpYoGbP1kPb9msBPSB6gbh+K8OMdxEz1NGqDmZYf4ZRUO8YYtZZoLD+6CozRiMmG29hVjvIldaPzOjR5MrYNWa8LDXZmdPMOgWUr794y4yjc0xQrGYgXX81xIznpaZ6uYUpLiFPf3qNmQFpJD+Z9oN0bot4wDFp3uRm60kzY0R6uoBMr+ptQ0y2TV57P+22E2m3vjdS/HC2HJxMZwcDabcMM6yhXVyDtbhFPQjNANGLSBOg/KfB7T9VLFNWKc+gkMLyQsHACFpFax4+eLDiOi634/G4E7ftWDzmOLGYHXdiFbbt2FOiwrElKf4ddhfLtTuDqD/tRaN7ECMvetF63It21yBWjvVharwPq9/3YTeqGQw+Q+U1jqqG/DcpuDuHmDaRbwZJDipi9VwVuEzhJaKYdLOA8johxFF3SbdyhN/xWWIG5ZlEWie4yBVL+B23xSIq5ybNjBZpKteuf1kOkEoYq58kkIh29BPwtWI1LedVVBTlUuFX0xJ2/QgcCkfztQDHdYoPLCU9WiABdgSyyBLhC/hCsYAifM50Ra4ZoqDzzdYlG2Im5Zu5FOoEt44b3cxbuV3AY2IxzRflXh6YlCfhIapn7G0mUe9JXu3lB0Q97eI7ppdG1WItlfG5k1PJLWeJePiLU4JK+eyfECptCrnXcx9RY18PbrPYRBv4+mlpE+QI+xeOSxNTa5piPk+UUQkvzsLZvU8+dWmiJXhUWH6mr+VNo8a9Y7pMw1jXzvwXsCl1ginmAIa8WcP2VKGPF6WK21rduJes8pFMcu52L54kV8o3ImMk6VzASK2RE23Gf/KAfxTW8dTfyBrqun6h2/hXvr8T/qHdfJta6c8nklvgM/eH4ns=

Correct stats should be (in game):
Hit: 1332 rating (15.09% for melee, 17.00% for spell)
Haste: 1155 rating
Mastery: 1566

Desktop (please complete the following information):
 - OS: Windows
 - Browser: Vivaldi
 - Version: 6.7.3329.35

**Comment by Tharre** [comment]
Adding up all the hit from items and gems I get 1213, same as the sim says.  Are you sure all the reforges are imported correctly? That's the most likely source of any stat differences.

Enchants, gems and socket boni all work fine unless the tooltip differ from what they are in-game somehow.

**Comment by polocabbit** [comment]
I'm also seeing incorrect values when importing from the addon. I should be at 1127 hit rating, but the sim has it as 1084. The errors I found are:

- Gloves: `Crit -> Mastery` should be `Crit  -> Hit`
- Belt: `Mastery -> Hit` should be `Expterise -> Hit`
- Boots: `Mastery -> Hit` should be `Haste -> Hit`

https://wowsims.github.io/cata/rogue/assassination/#eJzlkU9IFFEcx9/v95td1xfhc/HwFMJtKBgE4c3MxYqYUQg8etxuBiYdOkS3bnuKTToIhpt7ECSCEAKPS9FfZFfJ2mmDKKnQYFghYUs87LH3drx46KB163ua7/f7Prwvb/jZDAgI4RrcgCLAfYBHAC8BPgHsABQQiggrCGNc6kPjkNfHsmxgJVWm9MT1K7eu3sykRHpgHXhWvIhI/srZ3csLVhzRdkS8Syw3ySkB7xHzVZJbp2y6XSJnDnTztELOjGnmqmSn6yXam+80XHxrkQ3MmQUuxHaT5NdB29ovETPtCfF8lWxkzHlo2HuG1aBhF4GfFG8qJHcHDa57S9xtmhHlZIQl2hVjf+ibl4zdahlbWz1Y9O69+bB5BlX/BOZx0hp6jLwN7D9VVh2VOM/G2Cb08h79J0BiDp2+S283Ni4+wQvK933PV8r1Xc9zXeV77rBSOjisYc9k3qHsNZ7JrMUoPtdRvooxV43RqcWoPtRx5GcDw70Gju83cA2tCLs2kX1HlLCDU0uUrLoczhCzv2B3xxWmw94k7wv7ywtG68G5JImC09MdfQxG9W6t3cB7gLm8TA0V8Z886p/k3AmPgxWmasfi/kbJYz1rhaOJbweT8Btxb5CI

`{"talents":"0333230013122110321-0030000000000000000-2030020000000000000","glyphs":{"minor":[{"spellID":58032},{"spellID":58033},{"spellID":58038}],"prime":[{"spellID":63268},{"spellID":56801},{"spellID":63249}],"major":[{"spellID":63254},{"spellID":63256},{"spellID":56804}]},"class":"rogue","unit":"player","race":"Human","name":"Polocabbit","gear":{"items":[{"id":59455,"gems":[68778,59493,59489],"enchant":4209},{"id":62378,"gems":[],"reforging":151},{"id":58134,"gems":[52102],"reforging":147,"enchant":3808},{"id":56379,"gems":[],"reforging":138},{"id":58131,"gems":[52175,52082],"reforging":147},{"id":63454,"gems":[],"reforging":144},{"id":62433,"gems":[52212],"reforging":147,"enchant":4061},{"id":57918,"gems":[42143],"reforging":165},{"id":58132,"gems":[52082,52082],"reforging":158},{"id":56395,"gems":[42143],"reforging":165,"enchant":4076},{"id":62348,"gems":[]},{"id":62362,"gems":[],"reforging":151},{"id":56440,"gems":[]},{"id":56427,"gems":[],"reforging":161},{"id":63456,"gems":[]},{"id":57927,"gems":[],"reforging":147},{"id":59598,"gems":[],"reforging":147}]},"professions":[{"name":"Engineering","level":525},{"name":"Jewelcrafting","level":515}],"level":85,"spec":"assassination","realm":"Pagle"}`

**Comment by NoSkills** [comment]
Alright - I only checked whether items were reforged or not; which they were.

The issue is that using the addon; some reforged items will be reforged into something else (for whatever reason).

{"talents":"0333230013122110321-0020000000000000000-2030030000000000000","glyphs":{"minor":[{"spellID":58033},{"spellID":58038},{"spellID":58039}],"prime":[{"spellID":63249},{"spellID":56801},{"spellID":63268}],"major":[{"spellID":56811},{"spellID":56804},{"spellID":63256}]},"class":"rogue","unit":"player","race":"NightElf","name":"Tyríela","gear":{"items":[{"id":59455,"gems":[68778,59493,59480],"enchant":4209},{"id":62378,"gems":[],"reforging":165},{"id":56273,"gems":[52212],"reforging":161,"enchant":4204},{"id":65177,"gems":[],"enchant":1099},{"id":56562,"gems":[52258],"reforging":147,"enchant":4063},{"id":63454,"gems":[],"reforging":144,"enchant":3845},{"id":62433,"gems":[52145],"reforging":147,"enchant":4061},{"id":56537,"gems":[52258,52212]},{"id":56309,"gems":[42143,52102],"reforging":140,"enchant":4122},{"id":56395,"gems":[52102],"reforging":165,"enchant":4076},{"id":62362,"gems":[]},{"id":62348,"gems":[]},{"id":56394,"gems":[]},{"id":56440,"gems":[]},{"id":56302,"gems":[],"enchant":3789},{"id":56335,"gems":[],"enchant":3789},{"id":56420,"gems":[],"reforging":147}]},"professions":[{"name":"Engineering","level":525},{"name":"Jewelcrafting","level":511}],"level":85,"spec":"assassination","realm":"Firemaw"}

The errors are the following:
Gloves: Crit -> Mastery (should be Crit -> Hit)
Shoulders: Expertise -> Mastery (should be Expertise -> Hit)

**Comment by NoSkills** [comment]
Alright - I only checked whether items were reforged or not; which they were.

The issue is that using the addon; some reforged items will be reforged into something else (for whatever reason).

{"talents":"0333230013122110321-0020000000000000000-2030030000000000000","glyphs":{"minor":[{"spellID":58033},{"spellID":58038},{"spellID":58039}],"prime":[{"spellID":63249},{"spellID":56801},{"spellID":63268}],"major":[{"spellID":56811},{"spellID":56804},{"spellID":63256}]},"class":"rogue","unit":"player","race":"NightElf","name":"Kek","gear":{"items":[{"id":59455,"gems":[68778,59493,59480],"enchant":4209},{"id":62378,"gems":[],"reforging":165},{"id":56273,"gems":[52212],"reforging":161,"enchant":4204},{"id":65177,"gems":[],"enchant":1099},{"id":56562,"gems":[52258],"reforging":147,"enchant":4063},{"id":63454,"gems":[],"reforging":144,"enchant":3845},{"id":62433,"gems":[52145],"reforging":147,"enchant":4061},{"id":56537,"gems":[52258,52212]},{"id":56309,"gems":[42143,52102],"reforging":140,"enchant":4122},{"id":56395,"gems":[52102],"reforging":165,"enchant":4076},{"id":62362,"gems":[]},{"id":62348,"gems":[]},{"id":56394,"gems":[]},{"id":56440,"gems":[]},{"id":56302,"gems":[],"enchant":3789},{"id":56335,"gems":[],"enchant":3789},{"id":56420,"gems":[],"reforging":147}]},"professions":[{"name":"Engineering","level":525},{"name":"Jewelcrafting","level":511}],"level":85,"spec":"assassination","realm":"Firemaw"}

The errors are the following:
Gloves: Crit -> Mastery (should be Crit -> Hit)
Shoulders: Expertise -> Mastery (should be Expertise -> Hit)

**Comment by rosenrusinov** [comment]
@NoSkills we found some issues with the exporter parsing spirit and mastery enchants as reforges. We will have a fix soon and I'll tag you when a new version of the addon is up

**Comment by rosenrusinov** [comment]
@NoSkills we have pushed a new version of the addon. Can you try exporting your character again to confirm if it fixed the wrong imports for you

**Comment by polocabbit** [comment]
@rosenrusinov looks like reforge importing is still incorrectly mapping values. [For my provided example](https://github.com/wowsims/cata/issues/530#issuecomment-2134167872), all 3 are still incorrectly imported as of v0.0.7.

**Comment by MichaelRoehrig** [comment]
Can confirm, legs and shoulders are wrong for my rogue: `{"talents":"0333230013122110321-0020000000000000000-2030030000000000000","glyphs":{"minor":[{"spellID":58038},{"spellID":58039},{"spellID":58032}],"prime":[{"spellID":63249},{"spellID":63268},{"spellID":56801}],"major":[{"spellID":63254},{"spellID":56804},{"spellID":56811}]},"class":"rogue","unit":"player","race":"Troll","name":"Bonwart","gear":{"items":[{"id":59455,"gems":[68778,59489,59493],"enchant":4209},{"id":69827,"gems":[],"reforging":153,"random_suffix":-136},{"id":56273,"gems":[52212],"reforging":154,"enchant":4204},{"id":62361,"gems":[],"reforging":154,"enchant":1099},{"id":65060,"gems":[52212,52212],"reforging":146,"enchant":4063},{"id":56409,"gems":[],"reforging":154,"enchant":4089},{"id":62417,"gems":[52212],"reforging":147,"enchant":4061},{"id":56537,"gems":[52212,52212]},{"id":60300,"gems":[52204,52220],"reforging":168,"enchant":4126},{"id":58482,"gems":[52220],"reforging":147,"enchant":4076},{"id":62362,"gems":[],"reforging":153,"enchant":4079},{"id":67136,"gems":[],"reforging":154,"enchant":4079},{"id":58181,"gems":[]},{"id":62463,"gems":[],"reforging":168},{"id":56302,"gems":[],"reforging":168,"enchant":4083},{"id":56335,"gems":[],"reforging":151,"enchant":4083},{"id":68608,"gems":[],"reforging":151}]},"professions":[{"name":"Engineering","level":525},{"name":"Enchanting","level":525}],"level":85,"spec":"assassination","realm":"Venoxis"}`

**Comment by rosenrusinov** [comment]
> @rosenrusinov looks like reforge importing is still incorrectly mapping values. [For my provided example](https://github.com/wowsims/cata/issues/530#issuecomment-2134167872), the gloves are still incorrectly imported as of v0.0.7.

The version of the websim doesnt matter. The problem is in the exporting with the Addon and not with the importing of the website. We pushed a new version of the addon that should cover more cases but we are already getting reports that some of the enchants are still messing with this.
